#!/usr/bin/env bash
# pr_manager.sh — Create/update pull requests in target repos
set -euo pipefail

GITHUB_API="https://api.github.com"

# Create a PR with generated specs in a target repo
# Usage: pr_create <repo_dir> <repo_name> <spec_files...>
pr_create() {
  local repo_dir="$1"
  local repo_name="$2"
  shift 2
  local spec_files=("$@")

  if [[ ${#spec_files[@]} -eq 0 ]]; then
    repo_line "${DIM}No specs to PR${NC}"
    return 0
  fi

  local branch="rsi/audit-${AUDIT_DATE}"

  # Use the GitHub Actions token when operating on the workflow's own repo (PAT may not cover it)
  local api_token="$GH_TOKEN"
  if [[ -n "${GITHUB_ACTIONS_TOKEN:-}" && "${GITHUB_REPOSITORY:-}" == "${GITHUB_USERNAME}/${repo_name}" ]]; then
    api_token="$GITHUB_ACTIONS_TOKEN"
  fi

  cd "$repo_dir"

  # Check for existing open RSI audit PR
  local existing_pr
  existing_pr="$(curl -sf \
    -H "Authorization: token ${api_token}" \
    -H "Accept: application/vnd.github+json" \
    "${GITHUB_API}/repos/${GITHUB_USERNAME}/${repo_name}/pulls?head=${GITHUB_USERNAME}:${branch}&state=open" \
    | jq '.[0].number // empty' 2>/dev/null)" || true

  # Configure git for commits
  git config user.name "RSI Audit Agent"
  git config user.email "rsi-audit@noreply.github.com"

  # Create and switch to branch
  git checkout -b "$branch" 2>/dev/null || git checkout "$branch" 2>/dev/null || {
    log_error "Failed to create branch ${branch} in ${repo_name}"
    cd - > /dev/null
    return 1
  }

  # Stage spec files
  git add specs/features/ 2>/dev/null || true

  # Check if there are changes to commit
  if git diff --cached --quiet; then
    repo_line "${DIM}No changes to commit${NC}"
    cd - > /dev/null
    return 0
  fi

  # Commit
  local spec_count=${#spec_files[@]}
  git commit -m "$(cat <<EOF
RSI Audit: ${spec_count} improvement spec(s) (${AUDIT_DATE})

Generated by the RSI (Recursive Self-Improvement) audit system.
Each spec proposes a specific, actionable improvement found during
automated analysis of this repository.

Specs are in draft status and require human review before implementation.
EOF
)" || {
    log_error "Failed to commit specs in ${repo_name}"
    cd - > /dev/null
    return 1
  }

  git remote set-url origin "https://x-access-token:${api_token}@github.com/${GITHUB_USERNAME}/${repo_name}.git"

  # Push branch (force-push since audit branches are always overwritten)
  retry 3 2 git push --force -u origin "$branch" || {
    log_error "Failed to push branch ${branch} to ${repo_name}"
    cd - > /dev/null
    return 1
  }

  # Build PR body
  local pr_body
  pr_body="## RSI Audit Results — ${AUDIT_DATE}

### Generated Specs

| Spec ID | Title | Priority |
|---------|-------|----------|"

  for spec_file in "${spec_files[@]}"; do
    local spec_id spec_title spec_priority
    spec_id="$(yq -r '.metadata.id' "$spec_file" 2>/dev/null || echo "unknown")"
    spec_title="$(yq -r '.metadata.title' "$spec_file" 2>/dev/null || echo "unknown")"
    spec_priority="$(yq -r '.metadata.priority' "$spec_file" 2>/dev/null || echo "medium")"
    pr_body="${pr_body}
| ${spec_id} | ${spec_title} | ${spec_priority} |"
  done

  pr_body="${pr_body}

### About
These specs were generated by the [RSI Audit System](https://github.com/${GITHUB_USERNAME}/rsi) — an AI-powered recursive self-improvement pipeline.

- All specs are in **draft** status and require human review
- Each spec follows the A-SDLC feature specification format
- Web research logs are stored in the [rsi repo](https://github.com/${GITHUB_USERNAME}/rsi/tree/main/logs/research/)

### How to use
1. Review each spec file in \`specs/features/\`
2. Approve specs worth implementing (change status to \`approved\`)
3. Discard irrelevant specs by closing this PR or deleting individual files"

  if [[ -n "${existing_pr:-}" ]]; then
    # Update existing PR
    curl -sf \
      -X PATCH \
      -H "Authorization: token ${api_token}" \
      -H "Accept: application/vnd.github+json" \
      "${GITHUB_API}/repos/${GITHUB_USERNAME}/${repo_name}/pulls/${existing_pr}" \
      -d "$(jq -nc --arg body "$pr_body" '{body: $body}')" > /dev/null || true
    repo_line "${SYM_CHECK} Updated PR #${existing_pr}"
  else
    # Create new PR
    local pr_title="RSI Audit: ${spec_count} improvement spec(s) (${AUDIT_DATE})"
    local default_branch
    default_branch="$(curl -sf \
      -H "Authorization: token ${api_token}" \
      -H "Accept: application/vnd.github+json" \
      "${GITHUB_API}/repos/${GITHUB_USERNAME}/${repo_name}" \
      | jq -r '.default_branch // "main"')"

    local pr_response
    pr_response="$(curl -s -w "\n%{http_code}" \
      -X POST \
      -H "Authorization: token ${api_token}" \
      -H "Accept: application/vnd.github+json" \
      "${GITHUB_API}/repos/${GITHUB_USERNAME}/${repo_name}/pulls" \
      -d "$(jq -nc \
        --arg title "$pr_title" \
        --arg body "$pr_body" \
        --arg head "$branch" \
        --arg base "$default_branch" \
        '{title: $title, body: $body, head: $head, base: $base}')")"
    local http_code
    http_code="$(echo "$pr_response" | tail -1)"
    pr_response="$(echo "$pr_response" | sed '$d')"
    if [[ "$http_code" -lt 200 || "$http_code" -ge 300 ]]; then
      log_error "Failed to create PR for ${repo_name} (HTTP ${http_code}): $(echo "$pr_response" | jq -r '.message // .' 2>/dev/null)"
      cd - > /dev/null
      return 1
    fi

    local pr_number pr_url
    pr_number="$(echo "$pr_response" | jq -r '.number')"
    pr_url="$(echo "$pr_response" | jq -r '.html_url')"
    repo_line "${SYM_CHECK} ${GREEN}PR #${pr_number}${NC} ${DIM}${pr_url}${NC}"

    # Add labels
    curl -sf \
      -X POST \
      -H "Authorization: token ${api_token}" \
      -H "Accept: application/vnd.github+json" \
      "${GITHUB_API}/repos/${GITHUB_USERNAME}/${repo_name}/issues/${pr_number}/labels" \
      -d '{"labels":["rsi-audit","automated"]}' > /dev/null 2>&1 || true

    PRS_OPENED=$((PRS_OPENED + 1))
  fi

  cd - > /dev/null
}
